### ISSUE TITLE
Trufflehog does not work on arm64 systems

### ISSUE THREAD

**Issue by RahulVivekNair** [rs-loves-bugs/xsshunter#1]
When deploying to an arm64 server like those on oracle cloud, the trufflehog container does not work as it is pulling a hardcoded amd64 linux image in the dockerfile.trufflehog from github.

This can be fixed by pulling the correct architecture from the release page based on the system architecture.

**Comment by rs-loves-bugs** [comment]
Thanks for your contribution, pull request https://github.com/rs-loves-bugs/xsshunter/pull/2 merged!
