### ISSUE TITLE
SSL error 

### ISSUE THREAD

**Issue by yechielw** [rs-loves-bugs/xsshunter#12]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behavior

app should display after setting up environment

### Actual Behavior

frontend server return ssl errors

```bash
curl https://localhost:8080
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:8080

wget https://localhost:8080
--2024-01-23 10:11:16--  https://localhost:8080/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
OpenSSL: error:0A000126:SSL routines::unexpected eof while reading
Unable to establish SSL connection.

 openssl s_client -connect 127.0.0.1:8080
CONNECTED(00000003)
40B7F88AA07F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:../ssl/record/rec_layer_s3.c:303:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 293 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---

```

there is no documentation on how to setup or disable SSL 

### Steps to Reproduce

1. setup dns
2. run docker compose up
3. try accessing the server
4. experience an error

## Environment
 * OS: Ubuntu 
 * Version 23.10

## Additional Context
I tried as well to setup the environment using nginx with no success

**Comment by rs-loves-bugs** [comment]
Are you trying to run this locally(looks locally) or on a server with a public ip address? Do you have the domains pointing to that ip address?

**Comment by yechielw** [comment]
i am running on DigitalOcean instance 
Am i missing something? i didnt see anything about certificate setup. i do have my own certificate i use with nginx but I did not see a way to disable SSL for the app itself

**Comment by rs-loves-bugs** [comment]
Where you run `docker compose up -d` it will spin up the application in containers. One container has Caddy in it, a web server that will automatically setup ssl from Let's Encrypt and will proxy requests to the XSSHunter app container 

If you want to run your own web server you can start all the containers needed for XSSHunter app without Caddy with this command.

`docker compose up -d xsshunterexpress-db xsshunterexpress-service xsshunterexpress-trufflehog`

After this you will need to setup nginx the way you want it, with your ssl certs and a reverse proxy to 127.0.0.1:8080 so requests can reach XSSHunter app container. Here's an example config for nginx that can get you started:

https://github.com/rs-loves-bugs/xsshunter/blob/main/nginx.conf

**Comment by xinyuan-404** [comment]
nginx was started locally as you said, but the access admin.example.com showed 502 Bad Gateway

**Comment by rs-loves-bugs** [comment]
> nginx was started locally as you said, but the access admin.example.com showed 502 Bad Gateway

Please open a new issue and share more details about your setup, this is not related to this one here.

**Comment by yechielw** [comment]
That's exactly my issues
The proxy  caddy or nginx return 502 because of the error on the node server

**Comment by rs-loves-bugs** [comment]
> That's exactly my issues The proxy caddy or nginx return 502 because of the error on the node server

Did you setup your .env file correctly? It looks like you're missing the session secret key env.

**Comment by yechielw** [comment]
you are totaly right! 
it works
![image](https://github.com/rs-loves-bugs/xsshunter/assets/41305372/1db71f91-6689-4c27-b7f6-2d2e35b91f71)
