### ISSUE TITLE
error installation

### ISSUE THREAD

**Issue by abdulsec** [rs-loves-bugs/xsshunter#4]
did you have any idea how to fix this ?
ERROR: The Compose file is invalid because:
Service xsshunterexpress-trufflehog has neither an image nor a build context specified. At least one must be provided.

**Comment by rs-loves-bugs** [comment]
Are you using `docker-compose` or `docker compose`, make sure you use `docker compose`.

If you still have issues can you give me more details on your setup please?

**Comment by abdulsec** [comment]
look i was using an old version of docker compose , now  i am able to  install it successfully

**Comment by RahulVivekNair** [comment]
> did you have any idea how to fix this ?
> ERROR: The Compose file is invalid because:
> Service xsshunterexpress-trufflehog has neither an image nor a build context specified. At least one must be provided.
> 

If it's still not working please share the commands you ran and your system info,will look into it
