### ISSUE TITLE
Add DOM respose.

### ISSUE THREAD

**Issue by thezakman** [rs-loves-bugs/xsshunter#6]
Is possible to add the DOM responde back, like it used to have in the original project?

**Comment by rs-loves-bugs** [comment]
Yeah, it will be added in a future release.

**Comment by thezakman** [comment]
I am trying myself to add some of the original content back in the tool.
Already made some working progress in the email template, will do in the
web interface later. If you like I could push the updates from my fork once
it's done. Cheers!

Em ter., 18 de abr. de 2023 07:17, _rs ***@***.***> escreveu:

**Comment by rs-loves-bugs** [comment]
That would be awesome, let me know when you think it's ready!

**Comment by savushkin-yauheni** [comment]
@thezakman @rs-loves-bugs 
HI everyone! 
Is it a chance that the feature would be implemented ?

**Comment by rs-loves-bugs** [comment]
> Is it a chance that the feature would be implemented ?

Sure, if I get a pull request I'll merge it.

**Comment by rs-loves-bugs** [comment]
Added in v0.0.7
